### ISSUE TITLE
Add .gitignore file

### ISSUE THREAD

**Issue by ajkauffmann** [StefanMaron/MSDyn365BC.Code.History#40]
Would it be an idea to add a standard .gitignore file? That helps in case we download symbols.

I suggest to take this file: https://github.com/github/gitignore/pull/3871/files

**Comment by StefanMaron** [comment]
Thanks for the idea! I will address this for sure.
I just need to do a complete rewrite of the repo to include this file in every single commit.

I plan to do this in january to also include some other fixes.

**Comment by StefanMaron** [comment]
Changed about 1400 commits so the gitignore should now be included in every single commit and in all branches in this repo

**Comment by ajkauffmann** [comment]
Super, thanks for all the work!
