### ISSUE TITLE
Warehouse Shipment Line : missing keyword var

### ISSUE THREAD

**Issue by ronnykwon** [StefanMaron/MSDyn365BC.Code.History#42]
I know it's absolutely not the place to report bug but I don't know where else I can do this so I'm reporting a bug on the Table Warehouse Shipment Line. 
The two following events are missing a keyword var for the parameter HideValidationDialog
local procedure OnCreatePickDocOnBeforeCreatePickDoc(var WarehouseShipmentLine: Record "Warehouse Shipment Line"; var WhseShptLine: Record "Warehouse Shipment Line"; var WhseShptHeader2: Record "Warehouse Shipment Header"; **HideValidationDialog**: Boolean; var IsHandled: Boolean)

local procedure OnBeforeCreatePickDoc(var WarehouseShipmentLine: Record "Warehouse Shipment Line"; WarehouseShipmentHeader: Record "Warehouse Shipment Header"; **HideValidationDialog**: Boolean; var IsHandled: Boolean)

I'm using BC v19.

I cannot print silently my warehouse picking activities

**Comment by StefanMaron** [comment]
This is the wrong place for this, sorry. If you are a partner you can submit that to MS directly, otherwise you should contact your partner to do so.
